services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfsseta.ApplyForLanding.dll"
    ports:
      - 8080:8080/tcp
    env_file:
      - path: .env
        required: false